lh_project/labhelpers/urls.py
#URLconf

#to call a view (in views.py), we need to map it to a URL
from django.conf.urls import patterns, url


from labhelpers import views


urlpatterns = patterns('',
    url(r'^$', views.HomepageView.as_view(), name='homepage'),
    url(r'^(?P<pk>\d+)/$', views.LabDetailView.as_view(), name='lab_detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/submit/$', views.submit, name='submit'),
)

#2nd MODIFICATION -- USING GENERIC VIEWS
'''
Note: the name of the matched pattern in the regexes of the 2nd and 3rd patterns has 
changed from <question_id> to <pk> (stands for primary key).
'''

#NEXT: delete some old, unneeded views (index, detail, results) in polls/views.py.

#1st MODIFICATION -- USING NON-GENERIC VIEWS
'''
#--ADDED NEW VIEWS IN views.py -- need to add url() calls:
urlpatterns = patterns('', 
    #ex: /polls/
    url(r'^$', views.index, name='index'), 
    #ex: /polls/5/  #calls the detail view (views.detail) and passes in anything after "polls/" -- so 5 is read as the question_id
    url(r'^(?P<question_id>\d+)/$', views.detail, name='detail'),
    #ex: /polls/5/results/  #using () around a pattern capture the text matched by that pattern and sends it as a arg to the view fn (in this case, the question_id gets passed as text)
    url(r'^(?P<question_id>\d+)/results/$', views.results, name='results'),
    #ex: /polls/5/vote/ #\d+ is a regex to match a sequence of digits (i.e. a number)
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)
'''

'''
If you want to change the URL of the polls detail view to something else, perhaps to 
something like polls/specifics/12/ instead of doing it in the template (or templates) you 
would change it in polls/urls.py:

...
# added the word 'specifics'
url(r'^specifics/(?P<question_id>\d+)/$', views.detail, name='detail'),
...
'''
#NOW, POINT THE ROOT URLconf AT THE polls.urls.py MODULE BY EDITING mysite/urls.py

lh_project/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
#admin.autodiscover()   #PYTHON-GETTING-STARTED

urlpatterns = patterns('',
    url(r'^labhelpers/', include('labhelpers.urls', namespace="labhelpers")),   #makes url: http://localhost:8000/labhelpers/
    url(r'^admin/', include(admin.site.urls)),                                  #makes url: http://localhost:8000/admin/
)


#import hello.views
#    url(r'^$', hello.views.index, name='index'),
#    url(r'^db', hello.views.db, name='db'),
#    url(r'^admin/', include(admin.site.urls)),

lh_project/labhelpers/models.py
import datetime

from django.db import models
from django.utils import timezone



#STUDENTS
class User(models.Model):
    user_name=models.CharField(max_length=50)   
    user_rin=models.IntegerField()      
    
    def __str__(self):
        return self.user_name             

#LAB NAME & ID
class Lab(models.Model):
    lab_id = models.IntegerField()
    lab_name = models.CharField(max_length=200)
    lab_type = models.CharField(max_length=8, default='STATIC')
   
    
    def __str__(self):
        return self.lab_name


#TOPICS (FOR QUESTIONS)
class Topic(models.Model):
    lab=models.ManyToManyField("self")  #changed from foreign key for lab class
    topic_id = models.IntegerField()
    topic_name = models.CharField(max_length=200)
    coach_data = models.TextField()
    
    def __str__(self):
        return self.topic_name


    
#LAB QUESTIONS
class Question(models.Model):
    lab = models.ForeignKey(Lab)    #each question is paired with a particular lab
    #topic = models.ManyToManyField("self")
    topic = models.ForeignKey(Topic)
    question_id = models.IntegerField()
    question_text = models.TextField()
    #TODO: add question image
    question_hint = models.TextField()
    
    def __str__(self):
        return self.question_text
    
#LAB ANSWERS
class Answer(models.Model):
    question = models.ForeignKey(Question)  #each answer is paired with a particular question
    correct_answer_text = models.CharField(max_length=200)
    wrong_answer_text_1 = models.CharField(max_length=200, default='')
    wrong_answer_text_2 = models.CharField(max_length=200, default='')
    wrong_answer_text_3 = models.CharField(max_length=200, default='')
    wrong_answer_text_4 = models.CharField(max_length=200, default='')
    def __str__(self):
        return self.correct_answer_text




#1st MODIFICATION
#    def was_published_recently(self):
#        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
#    was_published_recently.admin_order_field = 'pub_date'
#    was_published_recently.boolean = True
#    was_published_recently.short_description = 'Published recently?'

lh_project/labhelpers/views.py
from django.http import HttpResponse    #ADDED THIS
from django.template import RequestContext, loader #ADDED IN 2nd MODIFICATION
from django.shortcuts import render     #ADDED IN 3rd MODIFICATION
from django.http import Http404         #ADDED IN 4th MODIFICATION
from django.shortcuts import get_object_or_404, render #ADDED IN 5TH MODIFICATION
from django.shortcuts import get_object_or_404  #ADDED IN 6TH MODIFICATION
from django.http import HttpResponseRedirect    #ADDED IN 6TH MODIFICATION
from django.core.urlresolvers import reverse    #ADDED IN 6TH MODIFICATION

from labhelpers.models import Question, Answer, Lab, Topic   #ADDED THIS IN 2nd MODIFICATION

#1st MODIFICATION:
#COMMENTED OUT in 2nd MODIFICATION (OVERWRITTEN BELOW)
'''
def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")
    
    #call this view from polls/urls.py
'''

#ADDING MORE VIEWS IN 1st MODIFICATION:
'''
def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)
'''

#4th MODIFICATION -- overwrite def detail()
'''
#The new concept here: The view raises the Http404 exception if a question with the requested ID doesn't exist.
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404
    return render(request, 'polls/detail.html', {'question': question})
'''
#5th MODIFICATION
'''
It's a very common idiom to use get() and raise Http404 if the object doesn't exist. 
Django provides a shortcut. Here's the detail() view, rewritten. 

The get_object_or_404() function takes a Django model as its first argument and an 
arbitrary number of keyword arguments, which it passes to the get() function of the model's 
manager. It raises Http404 if the object doesn't exist.

Why do we use a helper function get_object_or_404() instead of automatically catching the 
ObjectDoesNotExist exceptions at a higher level, or having the model API raise Http404 
instead of ObjectDoesNotExist?

Because that would couple the model layer to the view layer. One of the foremost design 
goals of Django is to maintain loose coupling. Some controlled coupling is introduced in 
the django.shortcuts module.

There's also a get_list_or_404() function, which works just as get_object_or_404() 
- except using filter() instead of get(). It raises Http404 if the list is empty.
'''
#8th MODIFICATION -- Comment out existing code and recreate at the bottom of file
'''
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html',{'question':question}) 
'''
 
#7th MODIFICATION -- almost the same as "def detail()" view
#now you need to create a template, aka:: .../polls/templates/polls/results.html 
'''
def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)
'''

#8th MODIFICATION -- Comment out existing code and recreate at the bottom of file
'''
def results(request, question_id):
    question=get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})
'''

#6th MODIFICATION -- overwrite dummy votes view with form action
'''
def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)
'''
'''
request.POST is a dictionary like object that lets you access submitted data by key name.
Here, request.POST['choice'] returns the ID of the selected choice, as a string.

request.POST values are always strings.
request.POST will raise KeyError if choice wasn't provided in POST data. The code checks 
for KeyError and redisplays the question form with an error msg if choice isn't given.

After incrementing the choice count, the code returns HttpResponseRedirect rather than 
HttpResponse. The former takes a single arg, the URL to which the user will be redirected.
* Always use HttpResponseRedirect after successfully dealing with POST data -- it's good
web dev practice.

The reverse() fn in HttpResponseRedirect helps avoid having to hardcode a URL in the view 
fn. It is given the name of the view that we want to pass control to and the variable 
portion of the URL pattern that points to that view.

Here, the reverse() call will return a string like: '/polls/3/results/' , where p.id = 3
The redirected URL will then call the 'results' view to display the final page.

request is an HttpRequest object

After someone votes in a question, the vote() view redirects to the results page for that 
question. See polls/views.py, under def results() 

'''

#8th MODIFICATION -- Comment out existing code and recreate at the bottom of file
'''
def vote(request, question_id):
    p=get_object_or_404(Question, pk=question_id)
    try:
        selected_choice=p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'polls/detail.html', {'question': p, 'error_message': "You didn't select a choice",})
    else:
        selected_choice.votes +=1
        selected_choice.save()
        #Always return an HttpResponseRedirect after successfully dealing with POST data.
        #This prevents data from being posted twice if a user hits the Back button
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))
'''
#NOW WIRE THESE NEW VIEWS INTO POLLS.URLS.PY MODULE BY ADDINT URL() CALLS

#ABOUT VIEWS
'''
Each view is responsible for doing one of two things: 
1.returning an HttpResponse object containing the content for the requested page, or 
2. raising an exception such as Http404. The rest is up to you.

Your view can read records from a database, or not. 
It can use a template system such as Django's - or a third-party Python template system - or not. 
It can generate a PDF file, output XML, create a ZIP file on the fly, anything you want, 
using whatever Python libraries you want.

All Django wants is that HttpResponse. Or an exception.
'''

'''
Because it's convenient, let's use Django's own database API, which we covered in Tutorial 1. 
Here's one stab at a new index() view, which displays the latest 5 poll questions in the system, 
separated by commas, according to publication date:
'''

#1st MODIFICATION (index)
'''
def index(request):
    lastest_question_list = Question.objects.order_by('_pub_date')[:5]
    output = ', '.join([p.question_text for p in latest_question_list])
    return HttpResponse(output)
'''
'''
There's a problem here, though: the page's design is hard-coded in the view. 
If you want to change the way the page looks, you'll have to edit this Python code. 
So let's use Django's template system to separate the design from Python by creating 
a template that the view can use.
'''


#2nd MODIFICATION
'''
This code loads the template in polls/templates/polls/index.html and passes it context.
The context is a dictionary mapping the template variable names to Python objects.

Load the page by pointing your browser at "/polls/", and you should see a bulleted-list 
containing the "What's up" question from Tutorial 1. The link points to the question's detail page.

It's a very common idiom to load a template, fill a context and return an HttpResponse 
object with the result of the rendered template.
'''
'''
def index(request):
    latest_question_list = Question.objects.order_by('pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = RequestContext(request, {
        'latest_question_list': latest_question_list,
    })
    return HttpResponse(template.render(context))
'''
    
#3rd MODIFICATION
'''
  - you no longer need to import loader, RequestContext, HttpResponse --unless you still 
  have the stub methods for detail, results, and vote:
  
from django.shortcuts import render

from polls.models import Question
'''
#8th MODIFICATION -- Comment out existing code and recreate at the bottom of file
'''
def index(request):
    latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)
'''
#ABOUT RENDER(arg1, arg2, arg3)
'''
The render() function takes the request object as its first argument, 
a template name as its second argument and a dictionary as its optional third argument. 
It returns an HttpResponse object of the given template rendered with the given context.
'''

#^----------------------END NON-GENERIC VIEWS ----------------------------^


#8th MODIFICATION
#USE GENERIC VIEWS: Less code is better 
'''
https://docs.djangoproject.com/en/1.7/intro/tutorial04/

The detail() (from Tutorial 3) and results() views are stupidly simple - and, as mentioned 
above, redundant. The index() view (also from Tutorial 3), which displays a list of polls, 
is similar.

These views represent a common case of basic Web development: getting data from the 
database according to a parameter passed in the URL, loading a template and returning the 
rendered template. Because this is so common, Django provides a shortcut, called the 
"generic views" system.

Generic views abstract common patterns to the point where you don't even need to write 
Python code to write an app.

Let's convert our poll app to use the generic views system, so we can delete a bunch of 
our own code. We'll just have to take a few steps to make the conversion. We will:

Convert the URLconf.
Delete some of the old, unneeded views.
Introduce new views based on Django's generic views.

Steps::
Amend polls/urls.py
Amend polls/views.py

'''
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone #ADDED IN 9TH MODIFICATION

from labhelpers.models import Answer, Question, Lab, Topic

lh_project/labhelpers/templates/labhelpers/homepage.html
<!--
Use Django's template system to separate the design from Python by creating a template that the view can use.

First, create a directory called templates in your polls directory. Django will look for templates in there.

Django's TEMPLATE_LOADERS setting contains a list of callables that know how to import 
templates from various sources. One of the defaults is 
django.template.loaders.app_directories.Loader which looks for a "templates" subdirectory 
in each of the INSTALLED_APPS - this is how Django knows to find the labhelpers templates even 
though we didn't modify TEMPLATE_DIRS, as we did in Tutorial 2.

We could have all our templates together, in one big templates directory, and it would 
work perfectly well. However, this template belongs to the polls application, so unlike the 
admin template we created in the previous tutorial, we'll put this one in the application's 
template directory (labhelpers/templates) rather than the project's (templates). We'll discuss 
in more detail in the reusable apps tutorial why we do this.

Within the templates directory you have just created, create another directory called labhelpers, 
and within that create a file called index.html (changed to homepage.html). In other words, your template should be at 
labhelpers/templates/labhelpers/homepage.html. Because of how the app_directories template loader works 
as described above, you can refer to this template within Django simply as labhelpers/homepage.html.

Now we might be able to get away with putting our templates directly in labhelpers/templates 
(rather than creating another labhelpers subdirectory), but it would actually be a bad idea. 
Django will choose the first template it finds whose name matches, and if you had a template 
with the same name in a different application, Django would be unable to distinguish between 
them. We need to be able to point Django at the right one, and the easiest way to ensure 
this is by namespacing them. That is, by putting those templates inside another directory 
named for the application itself.

bracket % load staticfiles % bracket loads the bracket % static % bracket template tag 
from the staticfiles template library. The bracket % static % bracket template tag 
generates the absolute URL of the static file.
-->
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'labhelpers/homepage.css' %}" />

<div id="main">
<div align="left">Labs </div>
    <p> 
        {% if lab_list %}
            <ul>
            {% for lab in lab_list %}
                <li><a href="{% url 'labhelpers:lab_detail' lab.id %}">{{lab.lab_name}}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No labs are available.</p>
        {% endif %}
	</p>
</div>

<div id="header">
	<div align="center">Lab Helpers </div>

<div id="left">Links </div>




<div id="footer">
	<div align="center">Dashboard </div>
</div>




<!--
"polls:detail" above points to the namespace "polls" of this app, defined in mysite/urls.py
-->

<!--
<li><a href="/polls/{{question.id }}/">{{question.question_text }}</a></li>    HARD CODED LINK :'0( 
-->

<!--
instead, remove specific URL reliance by using curly brackets % url % template tag
-->

<!--
The way this works is by looking up the URL definition as specified in the polls.urls.py module. 
You can see exactly where the URL name of ‘detail’ is defined below:

...
# the 'name' value as called by the % url % template tag
url(r'^(?P<question_id>\d+)/$', views.detail, name='detail'),
...
-->


<!--
Now let's update our index view in labhelpers/views.py to use the template:
-->

lh_project/labhelpers/templates/labhelpers/lab_detail.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'labhelpers/lab_detail.css' %}" />


<div id="main">
<div align="left">Lab Data: </div>
	<p> 
        {% if lab_data %}
        <ul>
            {% for question in questions %}
                <li>{{question.question_text}}</li>
            {% endfor %}
        </ul>
        {% else %}
            <p>No questions are available.</p>
        {% endif %}
    </p>
</div>
	

<!--
<link 

<h1>{{ lab.lab_name }}</h1>
<ul>
{% for answer in question.answer_set.all %}
    <li>{{answer.answer_text}}</li>
{% endfor %}
</ul>

-->

<!--
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'labhelpers:submit' question.id %}" method="post">
{% csrf_token %}
{% for answer in question.answer_set.all %}
    <input type="radio" name="answer" id=answer{{ forloop.counter }}" value="{{ answer.id }}"/>
    <label for="answer"{{ forloop.counter }}">{{ answer.answer_text }}</label><br />
{% endfor %}
<input type="submit" value="Submit" />
</form>
-->
<!--
The above template displays a radio button for each question choice. 
The value of ea radio button is the associated question choice's ID.

The name of ea radio button is "choice"
That means, when someone selects one of the radio buttons and submits the form, it'll send 
the POST data choice=# where # is the ID of the selected choice.

Using method="post" instead of method="get" to alter the data server side.

forloop.counter = # of times the "for" tag has gone through its loop

Django protects against Cross Site Request Forgeries (occur with "post" method)
 - all POST forms that are targeted at internal URLs should use the csrf token template tag
 
Now we need to create a view that handles the submitted data and does something with it:
EDIT polls/view.py
-->



<!-- 3rd MODIFICATION
<h1>{{question.question_text}}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{choice.choice_text}}</li>
{% endfor %}
</ul>
-->

<!--<?
ABOUT TEMPLATES::
The template system uses dot-lookup syntax to access variable attributes. 
In the example of {{ question.question_text }}, first Django does a dictionary lookup on 
the object question. 

Failing that, it tries an attribute lookup - which works, in this case. 
If attribute lookup had failed, it would've tried a list-index lookup.

Method-calling happens in the curly brackets: % for % loop: 
question.choice_set.all is interpreted as the Python code 
question.choice_set.all(), which returns an iterable of Choice objects and is suitable 
for use in the curly brackets % for % tag.
?> -->

<!--  2nd MODIFICATION
{{question}}
-->

<!-- 1st MODIFICATION
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <!--YOU NEED TO FIGURE OUT HOW TO CUSTOMIZE THIS TEMPLATE -->
         <li><a href="/polls/{{question.id }}/">{{question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No question details available. YOU NEED TO FIGURE OUT HOW TO CUSTOMIZE THIS TEMPLATE</p>
{% endif %}
-->

lh_project/labhelpers/templates/labhelpers/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for answer in question.answer_set.all %}
    <li>{{answer.answer_text }} -- {{ answer.submit }} submit{{ answer.submit|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'labhelpers:lab_detail' question.id %}">Answer again?</a>